apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: mern-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: mern-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: ATLAS_URI
              valueFrom:
                secretKeyRef:
                  name: mern-atlas-secret
                  key: ATLAS_URI
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
