{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    # Health check for ALB needs to know a valid path.
    # Frontend returns 200 on /, backend returns 200 on /api/healthcheck
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mern-backend
                port:
                  number: {{ $.Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}
